version: '3.8'

services:
  # Database Utama (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: ticketing_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ticketing_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Caching & Queue (Redis)
  redis:
    image: redis:alpine
    container_name: ticketing_redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
